### PR TITLE
177768210 allow edit email subject

### PR DESCRIPTION
**Pull request by tommywei110**
migration to add subject column to email template
update views for email template update -> update date email subject
add subject to seed_data

### CODE REVIEW

**Review by christopher-hou — COMMENTED** [review]
Is it possible to add a test or two for checking if the subject is actually changed upon editing?

**Comment by longhtong** [comment]
> Is it possible to add a test or two for checking if the subject is actually changed upon editing?

will do

**Review by christopher-hou — APPROVED** [review]
Awesome!

**Review by justinphyo — APPROVED** [review]
Looks good

**Pull request merged**
