### PR TITLE
Increased form test coverage

### PR DESCRIPTION
**Pull request by cscoder42**
After increasing test coverage I discovered two things: 
the bug still exists where you can submit a form for a new user and have it override an existing application
the fields "other" and "course" in the Teachers model seems to be useless

### CODE REVIEW

**Comment by christopher-hou** [comment]
Is this a finished PR or are you still working on it?

**Comment by cscoder42** [comment]
> Is this a finished PR or are you still working on it?

It's finished, but it contains the failing test that needs to be fixed, so CI won't pass.

**Review by christopher-hou — APPROVED** [review]
Tested this with my latest PR and it worked; once all the PRs are actually merged in I'll recheck and then hopefully merge this one as well

**Review by tommywei110 — APPROVED** [review]
LGTM

**Pull request merged**
